### ISSUE TITLE
Server authentication

### ISSUE THREAD

**Issue by dermatologist** [lhncbc/fhir-obs-viewer#7]
Thanks for the great project! I was wondering if there are any plans for building authentication support for services like Google healthcare API?

**Comment by plynchnlm** [comment]
It is something we would like to work on when we can get to it.  Are you interested in connecting to the Google Healthcare API in particular, or was that just an example?  Different services will have different authentication requirements.

**Comment by dermatologist** [comment]
Hi @plynchnlm,
My immediate interest is Google healthcare API. I did manage to POC Google API by injecting an externally generated OAuth token to fhir-batch-query.js. Cohort search works, but **pull data for the cohort** fails with:

 *conditional operations are not supported in API version V1*

On a different note, saving/exporting cohort as csv would be helpful.
Thanks!

**Comment by ChrisMeeusen** [comment]
I've been asked to look at standing up this app in our organization.  We have our own FHIR servers but they require authentication.  It looks like this app isn't setup to do a SMART launch with an EHR and provide that token to the server in the fhir api requests...?  Is that correct?  This only works in current state if the FHIR server it's calling doesn't require authentication?

**Comment by plynchnlm** [comment]
The app does do a SMART on FHIR launch; however we have not tested it with a FHIR server that requires authentication, so there could be something we missed.

**Comment by ChrisMeeusen** [comment]
> The app does do a SMART on FHIR launch; however we have not tested it with a FHIR server that requires authentication, so there could be something we missed.

I don't see how this app supports a SMART on FHIR launch in it's current state.  If you scan the package.json file you won't find any reference to a SMART on FHIR integration package, nor anything related to OIDC/OAuth2.  Furthermore there isn't any references to fetching a "smart-configuration"  in the code.  

This application in current state in the master branch does not appear to support a SMART on FHIR launch per http://www.hl7.org/fhir/smart-app-launch/example-app-launch-public.html#step-2-launch.  

I'm sure it can be linked to from an EHR but a simple link is not a SMART launch nor is there a path to point it at a standard EHR FHIR server because they will require Auth.

**Comment by plynchnlm** [comment]
You are right.  For some reason I was thinking you were asking about our SMART on FHIR Questionnaire app, (lforms-fhir-app), despite the fact that this issue was raised on fhir-obs-viewer.  This app is not currently a SMART on FHIR app.  Sorry for the confusion on that point.

Adding a SMART on FHIR launch for this app is on our to-do list, but as the current FHIR server we are targeting will not support SMART on FHIR authentication, it is not high in our priorities.  We would welcome a pull request for that feature.

**Comment by ChrisMeeusen** [comment]
Thank you for the clarification on current state.  The FHIR APIs we are looking to integrate aren't the ones provided by our EHR so we may end up doing a SMART on FHIR launch or we may end up doing some custom OAuth2 flow to our customized backend.  If we produce something that is reusable to the broader community we'll consider the PR route.  

Thanks!

**Comment by plynchnlm** [comment]
Thanks for considering that.  We are also going to increase the priority of creating a SMART on FHIR launch, though I would imagine it would be at least several weeks before we could complete that feature.

**Comment by plynchnlm** [comment]
fhir-obs-viewer now supports OAuth2 authentication-- consult the README.md file for details.
